### ISSUE TITLE
Owner of HomeSystem is wrong

### ISSUE THREAD

**Issue by JohannesHartUniKassel** [sekassel/stp-24-server-issues#11]
**Describe the bug**
A clear and concise description of what the problem is.

**To Reproduce**
1. Create a game
2. Change the users Empire to a empire and set game to started
3. See in Swagger that the only owner of a system has not the same id as the owner of the empire

**Expected behavior**
The userId of the system doesn't match the userId of the user who created the empire

**Additional context**
I only used one user (the host) to test it

**Comment by Clashsoft** [comment]
The owner of a system is the Empire `_id` not the Empire `user`.
