### ISSUE TITLE
Endpoint to check for current server version

### ISSUE THREAD

**Issue by Baldi-OG** [sekassel/stp-24-server-issues#12]
**Describe the feature you'd like**
We would like the server to provide an endpoint which returns the current version of the api.

**Where does the idea come from**
We want to locally store the presets provided by the server and only update them when there was a server-side update.
To achieve this we would like to also the version of the currently stored presets and check if there could have been changes.

**Describe alternatives you've considered**
-Updating the presets with every start of the game.
-Getting the needed preset every time it is needed in a controller

**Comment by Clashsoft** [comment]
Whats the problem with updating the presets with every start of the game? It does not take long (probably less time than the user needs to join a game), you can be sure to have the most recent version without any extra requests, and you don't need any file system logic (which involves problems like where to store the data).

**Comment by Baldi-OG** [comment]
We thought it would be a nicer solution to store the presents instead of getting them each time since they usually wont change and we would therefor be requesting the same data multiple times. 
But we will just request the preset each start of the game now and only cache them without saving to the file system.
