### ISSUE TITLE
System has link to itself

### ISSUE THREAD

**Issue by florianRt** [sekassel/stp-24-server-issues#16]
**Describe the bug**
In a game a system has a link to itself.

**To Reproduce**
1. Create a game (preferably with size 200)
2. sometimes a system now has a link to itself

A game with this would be: 
gameId = 6663065c3a20c8edba31764c
systemId = 6663066b3a20c8edba3176ce

**Expected behavior**
A system should not have a link to itself, only to other systems

**Comment by Clashsoft** [comment]
Fixed in the next update.
