### ISSUE TITLE
_public field for User 

### ISSUE THREAD

**Issue by AshkanKiafard** [sekassel/stp-24-server-issues#17]
**Is your feature request related to a problem? Please describe.**
We have an avatar maker, where players can choose between different portraits, background and frame. If we can save them in the server as one integer (or as 3 different integers), every player using the Calvario client can create new avatars and see the created avatars of other Calvario players. For example, 214 in server means second background, first frame and fourth frame for our clients.
Players from other clients will see the default avatar.

**Describe the solution you'd like**
Is it possible to add extra _public field to User schema as well so we can save the avatar digits here?

**Describe alternatives you've considered**
We have considered to merge all 3 images (portrait, background and frame) together and create a new image and save the url of this image but it would be more work than needed :)

**Additional context**
It would look like this:
![WhatsApp Image 2024-06-05 at 8 15 28 PM](https://github.com/sekassel/stp-24-server-tracker/assets/110186943/c6943a83-760e-4c97-9318-f4303e0ea2ad)

**Comment by Clashsoft** [comment]
Will be added in the next update.
