### ISSUE TITLE
Effects for Systems

### ISSUE THREAD

**Issue by AshkanKiafard** [sekassel/stp-24-server-issues#18]
**Is your feature request related to a problem? Please describe.**
We want to implement random events. We have one random event related to a certain type of system (golden islands/systems), where they give more resources to their owner, when this certain random event happens. Otherwise they give resources (or only consume resources). This gives players a choice. They can either capture this island before an event or not. 

If they do:
They lose resources with no benefit at the moment.
But when the random event happens, they get a lot of resources.

If they do not:
If random event happens and a player has already captured an golden island, they should fight to capture the island to get the benefits.

**Describe the solution you'd like**
Can System also have an effect field like empires?

**Describe alternatives you've considered**
We have considered to change how the event works. Random Islands are not shown on the map and cannot be captured until this random event happens. After the event, they are shown and can be captured to give players resources.
But then we would need a lot of more changes for server (Being able to change coordinates of a system, change neighbours of the system or being able to make islands invisible/private etc.)

**Additional context**
Random event  in question:
![random_events_golden_islands](https://github.com/sekassel/stp-24-server-tracker/assets/110186943/4ac96bab-e6da-49f9-9922-2f4fa424e059)

**Comment by Clashsoft** [comment]
Will be added in the next update.
