### ISSUE TITLE
Systems with no connection to other Systems

### ISSUE THREAD

**Issue by Daedalus706** [sekassel/stp-24-server-issues#19]
**Describe the bug**
I encountered a game with two systems with a connection to each other but no connection to the rest of the systems

**To Reproduce**
I can't reproduce the error, but I can provide the IDs of the game and the systems.
Game ID: `6669d93bc3e8953bc0f05ef4`
System IDs: `6669d942c3e8953bc0f05f86`, `6669d942c3e8953bc0f05f83`

```json
{
  "_id": "6669d942c3e8953bc0f05f83",
  "game": "6669d93bc3e8953bc0f05ef4",
  "links": {
    "6669d942c3e8953bc0f05f86": 16.431018607477462
  }
}
```
```json
{
  "_id": "6669d942c3e8953bc0f05f86",
  "game": "6669d93bc3e8953bc0f05ef4",
  "links": {
    "6669d942c3e8953bc0f05f83": 16.431018607477462
  }
}
```

**Expected behavior**
I assume that paths from every system to every other system should exist. If this is not the chase, this is not a bug.

**Additional context**
A similar issue has been reported on the STP Discord Server on 03.06.2024 by Johannes Hart

**Comment by Clashsoft** [comment]
Fixed in the next patch.
