### ISSUE TITLE
Add currentUsers (and maxUsers) to GET Games Endpoint

### ISSUE THREAD

**Issue by Baldi-OG** [sekassel/stp-24-server-issues#2]
**Is your feature request related to a problem? Please describe.**
Since it is only possible to get the members of one game at a time, it is not (without running into problems) possible to show the current member count of all games in the games-browser / lobby screen. 
It would be convenient to get this information directly from the get games endpoint.

Another idea we had was to show the current member count in relation to the max. member count of that game. 
E.g.
GameName 4/10 GameHost
But, to our knowledge, the server currently does not possess a way to store or access a max player value for games.

**Describe the solution you'd like**
Our solution proposes, that the GameSettings model will be extended with the optional field maxPlayers, containing an integer, and the Game model will be extended with the (optional) field currentPlayers.
CurrentPlayers could either be an integer storing the amount of players ingame or a list with ids of players in the game.
Declaring the fields as optional was considered so that other teams won't be forced to update their Models / logic to still be compatible with the new api version.

**Describe alternatives you've considered**
Alternatives we considered included:
-Not displaying this information in the game browser / lobby.
-Accepting long loading times for the current player count of the games. 
-Spoofing IP addresses to evade the rate limit.

**Additional context**
We don't know if the internal structure of the server would support both changes we suggest, if only one change can be implemented that would still be a positive outcome.
We contacted other teams about this and multiple members of 3 other teams supported this request.

**Comment by Clashsoft** [comment]
If other teams are interested in this change, please comment or react on this request.
