### ISSUE TITLE
When creating a game no systems get generated

### ISSUE THREAD

**Issue by AlexanderPineiro** [sekassel/stp-24-server-issues#20]
**Describe the bug**
After creating a new game the list of systems is empty, before this would happen for games where no player had an empire now it always happens

**To Reproduce**
Create a new game with one or more players which all have empires selected that where not broken in earlier versions
Below is a game object right after patching started=true.
```
Game[createdAt=2024-06-16T12:57:15.373Z, updatedAt=2024-06-16T12:57:35.163Z, _id=666ee12b4a
71cfb323c35ea4, name=test, owner=6632b1bc4682ddbd0d37987e, members=1, maxMembers=null, started=tr
ue, speed=0, period=0, settings=GameSettings[size=100]]
```

**Expected behavior**
The game initializes correctly with systems existing

**Additional context**
This doesn't seem to be caused by our implementation specifically because at least two other groups seem to have the same issue.
This is likely to be related to #19 because it started happening after the new server update.

**Comment by Clashsoft** [comment]
It should be fixed for now and will be properly addressed in the next patch.
