### ISSUE TITLE
Isolated Cluster of Systems

### ISSUE THREAD

**Issue by Daedalus706** [sekassel/stp-24-server-issues#21]
**Describe the bug**
I have found a game in which an isolated cluster of systems exists. 
This bug is probably similar to #19 just with larger clusters

**To Reproduce**
The gameId of the game with this bug is 66716f9b707c355a803a7eaa
To rule out any visual bugs, I used a breadth first search to verify that a cluster of systems, with no connection to any system outside the cluster, exists.

I have found a cluster of 9 systems
```
{
    '66716fab707c355a803a7f85', 
    '66716fab707c355a803a7f87', 
    '66716fab707c355a803a7f86', 
    '66716fab707c355a803a7f82', 
    '66716fab707c355a803a7f83', 
    '66716fab707c355a803a7f80', 
    '66716fab707c355a803a7f81', 
    '66716fab707c355a803a7f84', 
    '66716fab707c355a803a7f7f'
}
```

**Expected behavior**
There probably shouldn't be any isolated clusters

Edit: attached systems file 
[systems.json](https://github.com/user-attachments/files/15887521/systems.json)

**Comment by Clashsoft** [comment]
Hopefully fixed in v3.
