### ISSUE TITLE
District Job Result max capacity reached but at max yet

### ISSUE THREAD

**Issue by Daniel-Engelmann** [sekassel/stp-24-server-issues#23]
**Describe the bug**
A clear and concise description of what the problem is.
![image](https://github.com/sekassel/stp-24-server-tracker/assets/82509576/7078a95f-898b-4fff-928e-5db8d36fd9a8)
Currently I have 3 Cities and I am trying to add another City. The Max Cities is 14 but when trying to add the fourth City after the Job is completed the result says System is at Capacity.

**To Reproduce**
1. Create a job with type district and district=city
2. Wait until Job is completed
3. Print out the Result of the Job

**Expected behavior**
The Job completes succesfully

**Additional context**

**Comment by Clashsoft** [comment]
Is the total system capacity ~15 and do you have some buildings? All buildings and districts count towards the capacity.

**Comment by Daniel-Engelmann** [comment]
I didn't know there is a total system capacity but i just printed it out and its 22.
![image](https://github.com/sekassel/stp-24-server-tracker/assets/82509576/41198c44-3173-49f5-b8c9-6ebb989e89f1)
And i only have 15 Buildings build so there should be more than enough room for one more.

Here is the part of the Code:
![image](https://github.com/sekassel/stp-24-server-tracker/assets/82509576/871eb5ed-a98b-43be-bc1f-3f7f2a1594e4)

**Comment by Clashsoft** [comment]
Then I need the system ID to have a look.

**Comment by Daniel-Engelmann** [comment]
> Then I need the system ID to have a look.

6686585eba4143631bfb97c6

**Comment by Daniel-Engelmann** [comment]
Das sind alle Daten die mir swagger ausgibt:

{
  "_id": "6686585eba4143631bfb97c6",
  "game": "66865850ba4143631bfb96c9",
  "type": "regular",
  "districtSlots": {
    "city": 14.625,
    "industry": 14.625,
    "agriculture": 4,
    "energy": 3,
    "mining": 8
  },
  "districts": {
    "city": 3,
    "industry": 3,
    "mining": 3,
    "energy": 3,
    "agriculture": 3
  },
  "capacity": 22,
  "buildings": [
    "power_plant",
    "mine",
    "farm",
    "research_lab",
    "foundry",
    "factory",
    "refinery"
  ],
  "upgrade": "upgraded",
  "population": 25,
  "links": {
    "6686585eba4143631bfb97c7": 19.43922087814581,
    "6686585eba4143631bfb97c5": 24.27469028158775,
    "6686585eba4143631bfb97c3": 16.16724790217069
  },
  "x": 65.13300939327803,
  "y": -131.06803825718822,
  "effects": [],
  "createdAt": "2024-07-04T08:07:58.358Z",
  "updatedAt": "2024-07-04T08:36:15.973Z",
  "owner": "6686585eba4143631bfb970d"
}

**Comment by Clashsoft** [comment]
```json
"districts": {
"city": 3,
"industry": 3,
"mining": 3,
"energy": 3,
"agriculture": 3
},
"capacity": 22,
"buildings": [
"power_plant",
"mine",
"farm",
"research_lab",
"foundry",
"factory",
"refinery"
],
```
7 buildings + 15 districts = 22 (capacity). Everything adds up.

**Comment by Daniel-Engelmann** [comment]
Ah the building count towards it too okay thanks than we need to change that in our game.
