### ISSUE TITLE
Player Decision based Effects for Multistage events

### ISSUE THREAD

**Issue by 35529110** [sekassel/stp-24-server-issues#24]
**Is your feature request related to a problem? Please describe.**

As far as I can tell, it is currently only possible to have events that appear at random times or when a specific condition is met, like resources falling under a certain threshold. We have multi-stage event systems that don't fit into that framework.

**Describe the solution you'd like**

We need events that appear on the condition that another event has already happened and based on what our players decided during these events. The decision itself needs to be able to have a cost as well. Furthermore, we need the feature to have one of two events appear with a probability.

For example:

Event 1 happens and has effects X, Y, and decision A and B.
A costs 200 credits, B costs 100 credits.

We need a way to "delete" Resources for the decisions. Or the server needs to handle resource deletion

If the player chooses A: 
- Sub-event 1 happens with an 80% probability and MTTH 100.
- Sub-event 2 happens with a 20% probability and MTTH 120.

**Describe alternatives you've considered**

We currently don't see a way around this change, as effects and events are handled server-side.
We would be able to implement the decision tree client-side, but for that, we would need to have the ability to trigger the activation of an effect client-side.

**Additional context**

![image](https://github.com/sekassel/stp-24-server-tracker/assets/7688961/48734323-e2e3-4d78-b030-7963f187bf04)

Choosing "Install Cat Barriers" has a 75% chance that the next effect will be "Kitten Caught" and a 25% chance of it being "Computer Room Mayhem."

Choosing "okay" has a 100% that the next effect will be "Computer Room Mayhem"

**Comment by Clashsoft** [comment]
> we would need to have the ability to trigger the activation of an effect client-side.

You have that, you can change the empire `effects` however you want and using `_private` (or `_public`) you can store whatever other information you need for your event chains.

As for the costs, you can use the `resources` as you would with the market. I can add a query parameter so the empire does not earn credits, though.

<img width="731" alt="Screenshot 2024-07-04 at 14 38 18" src="https://github.com/sekassel/stp-24-server-tracker/assets/4145923/1b2bf8d5-23e8-4b83-a638-e047316fd5da">
