### ISSUE TITLE
Patching a GameMember resets HomeSystemType to null

### ISSUE THREAD

**Issue by ole-rumpf** [sekassel/stp-24-server-issues#26]
**Describe the bug**
If you patch a GameMember  with an EmpireTemplate which has an HomeSystemType selected the HomeSystemType of the response is null

EmpireTemplate of the member when updateGameMember is called :
![image](https://github.com/user-attachments/assets/dccefdc2-65a7-48c0-90de-74e6ea96499a)

EmpireTemplate of the response:
![image](https://github.com/user-attachments/assets/d0d5f763-58c2-4cc5-a8fa-5a90bfee8369)

**To Reproduce**
1. Create a new Game
2. Patch one GameMember with an EmpireTemplate that has a HomeSystemType selected with the coresponding server interface
3. Look at the HomeSystemType of the response
4. See error that HomeSystemType is null

**Expected behavior**
Patching a GameMember does not change the HomeSystemType of the GameMembers EmpireTemplate

**Comment by Clashsoft** [comment]
The property in `EmpireTemplate` is named `homeSystem` and not `homeSystemType`.

**Comment by ole-rumpf** [comment]
Oh, this explains it. Thank you, I did not recognize this. Now it works correctly.
