### ISSUE TITLE
Systems that overlap on each other

### ISSUE THREAD

**Issue by AlbertGesk** [sekassel/stp-24-server-issues#27]
<img width="960" alt="Screenshot 2024-07-21 182432" src="https://github.com/user-attachments/assets/c2836e68-8471-4a20-8077-a4409137ccf6">

<img width="758" alt="Screenshot 2024-07-24 195105" src="https://github.com/user-attachments/assets/28745b7a-2025-4a3c-92ba-c0b12351d600">

**Describe the bug**
- Sometimes systems locations are so close to each other, to the point that their icons end up overlapping, causing one of the system to be unreachable (un-clickable).
- I be alive it is usually two nodes/leafs which belong to two different sub-graphs that end up overlapping.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a game
2. look for error

**Expected behaviour**
Enough distance between systems to display them properly.

**Additional context**
Larger map size may increase the chance of error occurring.

**Comment by Clashsoft** [comment]
Fixed soon.
