### ISSUE TITLE
System Health Information always 0

### ISSUE THREAD

**Issue by 35529110** [sekassel/stp-24-server-issues#28]
**Describe the bug**
The Health Field of a System is always 0, meaning that a system always has 0 health.

**To Reproduce**
1. Create a game. Get the Gamesystem id
2. Do the server Request to display the current health of a system:
```shell
curl -X 'GET' \
  'https://stpellar.uniks.de/api/v4/games/66a6926f30dd7ab5470173c4/systems/66a6927e30dd7ab5470173f9' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjRmMzM4NzdkNDMwNWIxMThhODllMjEiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbm90aGVydXNlciIsImlhdCI6MTcyMjE5ODA2NCwiZXhwIjoxNzIyMjAxNjY0fQ.9wFc_pqSV0VRlomHGCJeNp6SrRk77TkHG6GkrOXzgpA'
``` 
3. See that it always returns 0 in the health field

**Expected behavior**
It should probably display the Maximum amount of health at the system start, and less if the system is damaged.

**Additional context**
I only tried this with the starting system, as we haven't implemented fleets yet
[response_1722198698505.json](https://github.com/user-attachments/files/16405158/response_1722198698505.json)

**Comment by Clashsoft** [comment]
Will be fixed in the next patch.
