### ISSUE TITLE
Allow game owner to kick members from the game

### ISSUE THREAD

**Issue by PygmalesDev** [sekassel/stp-24-server-issues#3]
**Is your feature request related to a problem? Please describe.**
This request covers the following that occurs while managing game lobby as a host:
Since it is currently not possible to set a limit on the number of simultaneous participants in the game, the game lobby can be filled with a large number of players. The more participants there are in the game, the more difficult it is for developers to adjust the gameplay, and this can spoil the gaming experience. Additionally, I should note that not all projects are likely to include the option to watch the game in spectator mode.

The lobby can get filled with "ghost players" who visited the lobby once and have not updated their readiness status since. Since only the player can remove themselves from the game, the only way to get rid of such a player is to delete the game itself, which results in the loss of progress and negatively impacts the gaming experience.

**Describe the solution you'd like**
- Give the game owner the ability to remove other game members on his decision (excluding the game owner).

**Describe alternatives you've considered**
Alternatively, allow the game owner to change the readiness status of other members.

**Additional context**
Such changes will have a positive impact on the gameplay and will provide developers with opportunities for more fine-tuned adjustments of the game lobbies.

**Comment by Clashsoft** [comment]
If other teams are interested in this change, please comment or react on this request.
