### ISSUE TITLE
Fleets can travel past enemy choke points

### ISSUE THREAD

**Issue by AlexanderPineiro** [sekassel/stp-24-server-issues#32]
**Describe the bug**
Travel jobs don't get paused when entering a battle making choke points useless as fleets can almost immediately disengage from combat into enemy territory.

**To Reproduce**
Send a ship into a system where it there is at least one system with enemies in the way.

**Expected behavior**
The fleet stops in the system with enemies until either side wins the battle (or they optionally retreat which I don't think will be possible to implement in the remaining time properly)

**Additional context**
If fleets are not locked into battle that makes any sort of defense almost impossible because it would be necessary to put a fleet into every single system you own, as a fast fleet could simply go past your main force and destroy all your systems.

**Comment by Clashsoft** [comment]
This is a good point. I fixed it and will make a patch soon.
