### ISSUE TITLE
Server has game with settingtype array 

### ISSUE THREAD

**Issue by ElenaSotoSobrino** [sekassel/stp-24-server-issues#5]
**Describe the bug**
In the Game model of the server is an attribute "settings" which should be an integer. But somehow another user of this server created a game with "settings" as an empty array. Now if we are loading all Games, there will be an error because an array cannot be converted to an integer. 

The Game has following attributes:
  "_id": "664df2647d4305b118a4733d",
  "name": "default",
  "owner": "662b83dea51a788b23a74d4b",
  "started": false,
  "speed": 1,
  "period": 0,
  "settings": [],
  "createdAt": "2024-05-22T13:25:56.541Z",
  "updatedAt": "2024-05-22T13:25:56.541Z",
  "members": 1

**Expected behavior**
Please delete this game and try to fix this, so user cannot create a game with setting with typ array

**Comment by PygmalesDev** [comment]
There are more than one instance of a such buggy game:
![изображение](https://github.com/sekassel/stp-24-server-tracker/assets/116347747/f2fbc733-731d-4e93-852e-60de3b610713)
id: 664e159f7d4305b118a4f48a
![изображение](https://github.com/sekassel/stp-24-server-tracker/assets/116347747/550c7aae-6f31-44e8-abdc-8cd6da052f1c)
id: 664dfc707d4305b118a4a4e0
![изображение](https://github.com/sekassel/stp-24-server-tracker/assets/116347747/9555d079-01ef-4611-b32d-cd6151b4f705)
id: 664df2647d4305b118a4733d

**Comment by Clashsoft** [comment]
I have deleted some but someone keeps creating more. I have changed the `string` user password to see who is the culprit.

**Comment by NoCodeNoBlunder** [comment]
I have found some configuration for the `Jackson` Deserializer we are using that allows to fix this issue to some extent.
The Sollution is enabling `ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT` see the code below.

```java
@Module
public class MainModule {
    @Provides
    @Singleton
     ObjectMapper mapper() {
        return new ObjectMapper()
            .enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
            .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
            .setSerializationInclusion(JsonInclude.Include.NON_ABSENT)
            .enable(SerializationFeature.INDENT_OUTPUT)
            // This Line can help.
            .enable(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT);
    }
}
```
