### ISSUE TITLE
Friendslist

### ISSUE THREAD

**Issue by Baldi-OG** [sekassel/stp-24-server-issues#7]
**Describe the feature you'd like**
Together with Phoenix Studio we would like to request a friendslist feature as discussed in our client meetings.

**Implementation suggestion**
Introduce a new api endpoint (/friends for example) with following functionalities:

- List all your friends
- Send a friend request to another user
- List all your open friend requests
- Decline / accept requests
- Remove friends 

The Declining / Accepting of requests could be handled by a single patch endpoint where either true of false
is passed.

**Alternative solution**
The entire process of requesting friends could also be removed if it would cause server side problems or if it would be
deemed too complex. In that case users could simply be marked as a friend in a one-sided fashion.
This would still require the the server to store information about a users friends but reduce the endpoints to:

- List all your friends
- Add friends
- Remove friends

**Comment by Clashsoft** [comment]
Please vote for this feature request. A representative of Phoenix Studio should comment on their preferred implementation (friend requests vs bare friend list). Both are possible from our side.

**Comment by Phanda1511** [comment]
Hello, 
I am Daniel Phan the PO of Phoenix Studio and my team and I would prefer the implementation of the bare friend list.

**Comment by Phanda1511** [comment]
Hello, 
I am a representative of Phoenix Studio.  We would like the friend requests feature.
We also propose adding a feature that allows players to invite friends to join a game. When a friend accepts the invitation, they should be directed to the game's member screen without needing to enter a game password.

Implementation Suggestions:

- Ability to decline or accept game invitations
- Display a list of all pending game invitations

**Comment by Clashsoft** [comment]
We will add friends and friend requests. Please make a separate proposal for game invites.
