### ISSUE TITLE
/api/v1/presets/technologies/tree not working

### ISSUE THREAD

**Issue by Baldi-OG** [sekassel/stp-24-server-issues#8]
**Describe the bug**
The endpoint [/api/v1/presets/technologies/tree](https://stpellar.uniks.de/api/v1#/Presets/PresetsController_getTechTree) does not work. It only produces an internal server error (500)

**To Reproduce**
1. Open swagger
2. Try to execute the endpoint

**Expected behavior**
Getting the svg of the technology tree

**Comment by Clashsoft** [comment]
Will be fixed in the next update.
