### ISSUE TITLE
Max members of a game can be larger then the integer limit

### ISSUE THREAD

**Issue by Baldi-OG** [sekassel/stp-24-server-issues#9]
**Describe the bug**
Setting the max members field of a game to a really really large value (>2,147,483,647)  instantly disables most game browser implementations, since it's to be expected that most teams implemented max members as an int.

**To Reproduce**
1. Post game with 999999999999 max member count
2. Game browser will die
3. For some reason patching it to less then max members afterwards does not seem to fix the problem
5. Only deleting the game will make it game browser function again

**Expected behavior**
Even though it is not explicitly stated in the server documentation, the server should not allow max member counts this high. The post/patch request should not be allowed.
 
**Additional context**
Maximum possible max members
![screenshot](https://github.com/sekassel/stp-24-server-tracker/assets/83312804/42a21c21-4256-477d-8713-907ad1b6d4f8)

This happens when 1 (or 8349834545) too many
![screenshot](https://github.com/sekassel/stp-24-server-tracker/assets/83312804/27a6b880-ddb0-4d1b-a8a4-77af850ec9bc)

**Comment by Clashsoft** [comment]
Will be fixed in the next update.
